name: Trading Log Updater
on: [push]
jobs:
  update-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit Logs
        run: |
          git config --global user.name "Bot"
          git pull
          git add logs/
          git commit -m "Auto-update trade logs"
          git push